
const zzz = `

about-section
accordion
accordion-item
ad-board
addthis-social-sticky-nav
allowed-fetched-schemas
amplience-video-carousel
artists_and_groups
asset-kit-item
award-year-winner
award-year-winners-config
awards-card
awards-history-carousel
awards-row
backstage-filters
body-text
brightcove-video-player
countdown-clock
collections-video-carousel
content-block
content-block-list
content-hero
content-page
content-row
content-row-item
contributor
credit
cta
curated-content
donation-widget
dynamic-video-carousel
executive
expandable-content
facebook-post-embed
featured-article-card
featured-pillar-card
featured-pillar-cards-row
home-hero-editorial-carousel
gallery
generic-content
generic-page-content
genre-details-landing-page
global-footer
global-footer
global-footer-content
global-footer-navigation
hamburger-menu
global-header
global-navigation
global-site-settings
google-ad
hero-carousel
hero-carousel-info-card
hero-carousel-info-cards
hero-slide
iframe-content
schema-media
impact-media-carousel
impact-media-slide
instagram-embed
landing-page
link-cards
mega-nav
member-discounts
member-notice-message
member-notices
membership-hero
membership-hero-item
meta-data
mission-statement
music_genre
global-navigation
home-page
muzooka-webhooks
news-article
news-carousel
newsletter-sign-up
nomination
page
partner
partner-logo-carousel
partner-logo-slide
performer
performers-grid
photo
pillar-navigation
press-release
program-banner
series-or-collection
series-video-carousel
show-year
simple-content-card
slide
social-media-carousel
subscribe-nav-content
subscribe-social-links
testimonial-carousel
text-banner
ticketing-page
top-full-banner
top-full-banner-carousel
top-subnav
tweet-embed
video
video-detail-content
video-embed-player
video-hero
video-playlist
legacy-vocabulary
youtube-subscribe-banner
video-embed-types
newsletter-site-partial
navigation
meta-data
meta-data
content
banner-content
`