const { exportCLI } = require("../../utils/executeCLI");

const schemaIds = [
    // partials
    "https://therecordingacademy.com/partial/meta-data",
    "https://therecordingacademy.com/partial/navigation",
    "https://therecordingacademy.com/partial/banner-content",
    "https://therecordingacademy.com/partial/content",
    "https://therecordingacademy.com/partial/legacy-vocabulary",
    
    // slots
    "https://therecordingacademy.com/slot/content-page",
    "https://therecordingacademy.com/slot/global-navigation",
    "https://therecordingacademy.com/slot/home-page",
    "https://therecordingacademy.com/slot/generic-page-content",
    "https://therecordingacademy.com/slot/home-hero-editorial-carousel",
    "https://therecordingacademy.com/slot/global-footer",

    //content
    "https://therecordingacademy.com/content/meta-data",
    "https://therecordingacademy.com/content/news-article",
    "https://therecordingacademy.com/content/partner-logo-slide",
    "https://therecordingacademy.com/content/generic-content",
    "https://therecordingacademy.com/content/iframe-content",
    "https://therecordingacademy.com/content/social-media-carousel",
    "https://therecordingacademy.com/content/genre-details-landing-page",
    "https://therecordingacademy.com/content/press-release",
    "https://therecordingacademy.com/content/series-or-collection",
    "https://therecordingacademy.com/content/backstage-filters",
    "https://therecordingacademy.com/content/cta",
    "https://therecordingacademy.com/content/show-year",
    "https://therecordingacademy.com/content/nomination",
    "https://therecordingacademy.com/content/performer",
    "https://therecordingacademy.com/content/global-site-settings",
    "https://therecordingacademy.com/content/video",
    "https://therecordingacademy.com/content/page",
    "https://therecordingacademy.com/content/video-playlist",
    "https://therecordingacademy.com/content/executive",
    "https://therecordingacademy.com/content/curated-content",
    "https://therecordingacademy.com/content/accordion-item",
    "https://therecordingacademy.com/content/expandable-content",
    "https://therecordingacademy.com/content/hamburger-menu",
    "https://therecordingacademy.com/content/pillar-navigation",
    "https://therecordingacademy.com/content/mission-statement",
    "https://therecordingacademy.com/content/addthis-social-sticky-nav",
    "https://therecordingacademy.com/content/donation-widget",
    "https://therecordingacademy.com/content/gallery",

    "https://therecordingacademy.com/content/content-block",
    "https://therecordingacademy.com/content/slide",
    "https://therecordingacademy.com/content/partner",
    "https://therecordingacademy.com/content/partner-logo-carousel",
    "https://therecordingacademy.com/content/newsletter-sign-up",
    "https://therecordingacademy.com/content/artists_and_groups",
    "https://therecordingacademy.com/content/testimonial-carousel",
    "https://therecordingacademy.com/content/program-banner",
    "https://therecordingacademy.com/content/body-text",
    "https://therecordingacademy.com/content/contributor",
    "https://therecordingacademy.com/content/credit",
    "https://therecordingacademy.com/content/content-block-list",
    "https://therecordingacademy.com/content/accordion",
    "https://therecordingacademy.com/content/impact-media-carousel",
    "https://therecordingacademy.com/content/photo",
    "https://therecordingacademy.com/content/impact-media-slide",
    "https://therecordingacademy.com/content/allowed-fetched-schemas",
    "https://therecordingacademy.com/content/hero-carousel-info-cards",
    "https://therecordingacademy.com/content/hero-carousel-info-card",
    "https://therecordingacademy.com/content/hero-carousel",
    "https://therecordingacademy.com/content/hero-slide",
    "https://therecordingacademy.com/content/accordion",
    "https://therecordingacademy.com/content/top-subnav",
    "https://therecordingacademy.com/content/global-footer-content",
    "https://therecordingacademy.com/content/global-footer-navigation",    
];

exportCLI({ schemaIds, client: "musicaresdev", toExport: "content-type-schema", name: "exported-content-schemas-musicares" })
